name: Gray Scott
favicon: null
layout_spectrum: 0.06413
typography_spectrum: 0.24951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#342a29'
    - '#b1bcce'
    - '#615c56'
    - '#8a8683'
    - '#ffffff'
  brandStrength: 0.6875
  lightness: 0.19739592028781772
  saturation: 0.10351482802070677
  rhythmicContrast: 0.3172360584139824
purpose: []
