name: Gray Scott
favicon: null
layout_spectrum: 0.02853
typography_spectrum: 0.72586
title: GRAY SCOTT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#342a29'
    - '#b1bcce'
    - '#615c56'
    - '#8a8683'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
